- hosts: "k8s-master"
  vars_prompt:
  - name: username
    prompt: 'Enter username'
    private: no
  - name: namespace
    prompt: "Enter namespace"
    private: no
  roles:
    - create-user-kubeconfig
